### 🔸 Q7. Flatten a 2D matrix and sort  
- Flatten a given 2D matrix.
- Sort all values in ascending order.


In [1]:
import numpy as np

In [23]:
_2Darray = np.random.rand(4,4)

In [24]:
_2Darray

array([[0.48934733, 0.03463751, 0.03797455, 0.06133842],
       [0.06247564, 0.38592566, 0.44368634, 0.39380793],
       [0.83385327, 0.78524116, 0.4108654 , 0.63965014],
       [0.69845193, 0.95951326, 0.872151  , 0.73180057]])

In [25]:
_1Darray = _2Darray.flatten()
_1Darray

array([0.48934733, 0.03463751, 0.03797455, 0.06133842, 0.06247564,
       0.38592566, 0.44368634, 0.39380793, 0.83385327, 0.78524116,
       0.4108654 , 0.63965014, 0.69845193, 0.95951326, 0.872151  ,
       0.73180057])

In [27]:
_1Darray.sort()
_1Darray

array([0.03463751, 0.03797455, 0.06133842, 0.06247564, 0.38592566,
       0.39380793, 0.4108654 , 0.44368634, 0.48934733, 0.63965014,
       0.69845193, 0.73180057, 0.78524116, 0.83385327, 0.872151  ,
       0.95951326])

In [29]:
array = _1Darray*100
array.astype(int)

array([ 3,  3,  6,  6, 38, 39, 41, 44, 48, 63, 69, 73, 78, 83, 87, 95])