### 🕸️ Q5. Create a correlation matrix manually using only NumPy functions.

In [1]:
import numpy as np

data = np.random.rand(5, 5)

In [2]:
def correlation_matrix_manual(data):
   n_features = data.shape[1]
   corr_matrix = np.zeros((n_features, n_features))
   
   # Calculate correlation for each pair of columns
   for i in range(n_features):
       for j in range(n_features):
           if i == j:
               corr_matrix[i, j] = 1.0  # Perfect correlation with itself
           else:
               # Get columns
               x = data[:, i]
               y = data[:, j]
               
               # Calculate means
               mean_x = np.mean(x)
               mean_y = np.mean(y)
               
               # Calculate correlation coefficient manually
               numerator = np.sum((x - mean_x) * (y - mean_y))
               denominator = np.sqrt(np.sum((x - mean_x)**2) * np.sum((y - mean_y)**2))
               
               corr_matrix[i, j] = numerator / denominator
   
   return corr_matrix

In [3]:

manual_corr = correlation_matrix_manual(data)


In [4]:
print("Manual correlation matrix:")
print(manual_corr)

Manual correlation matrix:
[[ 1.         -0.15585892  0.26468008 -0.11706808 -0.24734087]
 [-0.15585892  1.         -0.73774906  0.58034615  0.956412  ]
 [ 0.26468008 -0.73774906  1.         -0.96520654 -0.84763675]
 [-0.11706808  0.58034615 -0.96520654  1.          0.69887502]
 [-0.24734087  0.956412   -0.84763675  0.69887502  1.        ]]


In [5]:
print("\nNumPy corrcoef result:")
print(np.corrcoef(data.T))


NumPy corrcoef result:
[[ 1.         -0.15585892  0.26468008 -0.11706808 -0.24734087]
 [-0.15585892  1.         -0.73774906  0.58034615  0.956412  ]
 [ 0.26468008 -0.73774906  1.         -0.96520654 -0.84763675]
 [-0.11706808  0.58034615 -0.96520654  1.          0.69887502]
 [-0.24734087  0.956412   -0.84763675  0.69887502  1.        ]]
