## 🧮 Q10. Write a NumPy-only function to compute the determinant of a matrix using LU decomposition (without using np.linalg.det).
Goal: Implement determinant calculation manually using matrix factorization.
**np.random.seed(0)**
**A = np.random.randint(1, 10, size=(4, 4)).astype(float)**

In [2]:
import numpy as np

def pearson_corr_numpy(X):
    """
    Compute Pearson Correlation Coefficient Matrix using only NumPy.
    
    Args:
        X (ndarray): shape (n_samples, n_features)
    
    Returns:
        corr_matrix (ndarray): shape (n_features, n_features)
    """
    # Center the data (subtract mean column-wise)
    X_centered = X - X.mean(axis=0)
    
    # Compute covariance matrix
    cov_matrix = X_centered.T @ X_centered / (X.shape[0] - 1)
    
    # Standard deviations
    std_dev = np.sqrt(np.diag(cov_matrix))
    
    # Outer product of std_dev to get denominator matrix
    denom = np.outer(std_dev, std_dev)
    
    # Avoid division by zero
    denom[denom == 0] = 1e-10
    
    # Pearson correlation = covariance / (std_x * std_y)
    corr_matrix = cov_matrix / denom
    return corr_matrix


In [3]:
np.random.seed(0)
X = np.random.rand(100, 5)  # 100 samples, 5 features

corr_matrix = pearson_corr_numpy(X)
print("Pearson Correlation Matrix:\n", np.round(corr_matrix, 2))


Pearson Correlation Matrix:
 [[ 1.   -0.02  0.22  0.03  0.01]
 [-0.02  1.    0.03  0.16  0.08]
 [ 0.22  0.03  1.    0.06  0.15]
 [ 0.03  0.16  0.06  1.    0.05]
 [ 0.01  0.08  0.15  0.05  1.  ]]
